### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by nadia31415**
Changes:
* Sentieon version updated from v2.0.1 to v4.0.1
* Sentieon app configurations changed to use decoy sequences in reference genome
* Removed nivana_v2.0.1, nivana2vcf_v1.1.1 and region_coverage_v1.0.5
* Uses new TWE and CEN capture BED files for GRCh38 
* Uses new masked reference genome, FASTA and BWA indexed reference genome for GRCh38
* Uses new formatted omni25 VCF file for GRCh38 and sites VCF file for b38

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nadia31415)

___
*[`dxworkflow.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NL6XAUL3N67NINwdt8V:-NL6XAUL3N67NINwdt8W:bu19hc7) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/ecde244f7c471ffa463d60a51ac442756dcc7225/dxworkflow.json#L1)):*
> ```JSON
> {
> ```

Workflow needs to be obtained via `dx get` rather than `dx describe`



_Code quote:_
```JSON
{
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @nadia31415)

___
*[`dxworkflow.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NL6XAUL3N67NINwdt8V:-NLVmqe86HcoxXzBU3nj:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/ecde244f7c471ffa463d60a51ac442756dcc7225/dxworkflow.json#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Workflow needs to be obtained via `dx get` rather than `dx describe`
</blockquote></details>

Done
___
*[`dxworkflow.json` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NLVmvjR5toM-S9bdiGt:-NLVmvjR5toM-S9bdiGu:b-2eovha) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/a254d453c6a59e2ea6e7597da9b4e3c5e0c76d66/dxworkflow.json#L2)):*
> ```JSON
> {
>   "name": "dias_single_v2.0.0_ignore_decoy",
> ```

Should this be removed?



_Code quote:_
```JSON
_ignore_decoy
```
___
*[`README.md` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NLVn4lUA6f2ED0tqQ1Z:-NLVn4lV-XNWuqpLzwTN:btoa4xn) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/a254d453c6a59e2ea6e7597da9b4e3c5e0c76d66/README.md#L10)):*
> ```Markdown
> ## Release Notes:
> * Sentieon version updated from v2.0.1 to v4.0.1
> * Sentieon app configurations have been changed to adapt to using decoy sequences in reference genome
> ```

could we specify that this is during alignment?



_Code quote:_
```Markdown
Sentieon app configurations have been changed to adapt to using decoy sequences in reference genome
```
___
*[`README.md` line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NLVn9eP5hyAvKIUGDj-:-NLVn9eR2I-l5RgjEP-z:bh2am5k) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/a254d453c6a59e2ea6e7597da9b4e3c5e0c76d66/README.md#L12)):*
> ```Markdown
> * Sentieon app configurations have been changed to adapt to using decoy sequences in reference genome
> * Removed nivana_v2.0.1, nivana2vcf_v1.1.1 and region_coverage_v1.0.5 from Dias Single workflow
> * Uses new TWE and CEN capture BED files for GRCh38 
> ```

Are these part of this workflow? Should this be mentioned here?



_Code quote:_
```Markdown
Uses new TWE and CEN capture BED files for GRCh38
```

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12)* status: all files reviewed, 2 unresolved discussions (waiting on @nadia31415)

___
*[`dxworkflow.json` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NLVmvjR5toM-S9bdiGt:-NLb0_p64lz8I7L4CuKp:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/a254d453c6a59e2ea6e7597da9b4e3c5e0c76d66/dxworkflow.json#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Done

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[`README.md` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NLVn4lUA6f2ED0tqQ1Z:-NLeKcLE1FPdaOfjtP88:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/a254d453c6a59e2ea6e7597da9b4e3c5e0c76d66/README.md#L10)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

could we specify that this is during alignment?
</blockquote></details>

Done.
___
*[`README.md` line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12#-NLVn9eP5hyAvKIUGDj-:-NLeKfwhC5S_luwEASCd:b-6imlbu) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/a254d453c6a59e2ea6e7597da9b4e3c5e0c76d66/README.md#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Are these part of this workflow? Should this be mentioned here?
</blockquote></details>

Removed comment

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nadia31415)

**Pull request merged**
