### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by sophie22**
## Summary of changes:
- update executables from applet to app where available (verifybamid, samtools_flagstat)
- update executable to latest version with relevant improvements: sentieon from v2 to v4, somalier_extract has changes relevant for the move to Epic-style sample naming
- remove input files from workflow definition into the corresponding eggd_conductor config file (for CEN and WES)

### Example job:
Set off with eggd_conductor config version v1.1.1 for CEN: https://platform.dnanexus.com/projects/GQKqF7j47f0G6XzqyJvJP3Y2/monitor/analysis/GQj911Q47f0B4zzbFyGP4BVQ

For further details on this update please see: [DI-217](https://cuhbioinformatics.atlassian.net/browse/DI-217)

[DI-217]: https://cuhbioinformatics.atlassian.net/browse/DI-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15)

### CODE REVIEW

**Comment by sophie22** [comment]
need to update READme with version and link to eggd_conductor config for CEN and WES that this workflow is compatible with!

**Review by Addy81 — CHANGES_REQUESTED** [review]
Do you think we should add names to display apps in the gui with?  It seems to take the section after stage.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15#-:-NT-eoxX5oseZM60ApY9:byo1rvs)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @sophie22)

___
*[`README.md` line 9 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15#-NT-bq8X-kIsYVbOjrbl:-NT-bq8YA3cP234C8LGj:b-26mdhh) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/df9764ee82f97b2ffd30d795147197b109e6d4ed/README.md#L9)):*
> ```Markdown
> 
> ## Release Notes:
> * Updated README to current version
> ```

Should we have release notes within the readme? If we keep it we should update it to reflect what happened, but would be happy to ditch if we are sticking to github release notes.

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @mattgarner)

___
*[`README.md` line 9 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15#-NT-bq8X-kIsYVbOjrbl:-NTSnuFF1TZDVQl64Kjo:baqdx83) ([raw file](https://github.com/eastgenomics/eggd_dias_single_workflow/blob/df9764ee82f97b2ffd30d795147197b109e6d4ed/README.md#L9)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Should we have release notes within the readme? If we keep it we should update it to reflect what happened, but would be happy to ditch if we are sticking to github release notes.
</blockquote></details>

I added a short note that input files are removed from here, but I think Release notes can be easily found in the Releases if needed.

**Review by Addy81 — APPROVED** [review]
All apps as expected. To figure out why they get renamed to stage string in the next version.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15#-:-NTZASrB5vIYm8hqanAZ:b-a59j82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Comment by sophie22** [comment]
Single workflow set off manually (described in the Confluence page). Link to job: https://platform.dnanexus.com/projects/GQK67K04P1gy9xg5pP5vyXZY/monitor/analysis/GV36jQj4P1gZQPjjQ6KX8Vkf

**Review by Addy81 — APPROVED** [review]
Above shows naming issue might be due conductor, single ok to go.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/15#-:-NTrj16I16E0EUS1rzlR:b-uxuv4b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
