### PR TITLE
dias single 1.2.0

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Added mosdepth
- Stage ids updated because of new workflow version

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4)

### CODE REVIEW

**Review by jethror1 — COMMENTED** [review]
To check:
- sentieon has been changed from 2.0.1 to 2.1.0, is this intentional?
- no longer outputting sentieon output_metrics?
- this is removed "run_CollectMultipleMetrics": false?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4#-:-MMa4ovk1jZCHKOzJ06Q:b-w9ypec)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — COMMENTED** [review]
Please could you add more details about the changes to the PR. There appears to be more going on here than just adding mosdepth

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4#-:-MMaMhQO3mJITSxXMANZ:b-f0deam)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
Blocking until resolved

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4#-:-MMaNXh95qs0QVnrbWot:b-128xds)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by Yu-jinKim — COMMENTED** [review]
So when I first created the PR, i forgot some elements:
- output_metrics
- runCollectMultipleMetrics

`dx get` also doesn't output things in the same order which show more changes than there actually is

The stage ids changed but the only real difference is that mosdepth was added

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4#-:-MMpOeqM8EgQnLXwRs5R:b1dfrv6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by mattgarner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_single_workflow/4#-:-MMtDiRbCz6Ygka6j84l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
